# Generated by Django 3.2.8 on 2021-10-27 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211026_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'permissions': [('cancel_order', 'Can Cancel Order')]},
        ),
    ]
